[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = {mainnet = "https://eth-mainnet.g.alchemy.com/v2/n7CpQ8eQ8CKV4or5DAn_nAOaKvizeVG2"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config